package io.ecucore.transport

/**
 * Descrições dos códigos DTC "genéricos" padronizados pela SAE J2012 (faixa P0xxx/P2xxx/P3xxx,
 * C0xxx, B0xxx, U0xxx) — o significado desses códigos é o mesmo em qualquer fabricante, ao
 * contrário da faixa "fabricante" (P1xxx/C1xxx/B1xxx/U1xxx, segundo dígito 1), que varia por ECU
 * e não tem descrição padronizada aqui.
 */
object DtcDescriptions {
    private val GENERIC: Map<String, String> = mapOf(
        "P0100" to "Circuito do sensor de fluxo de massa de ar (MAF) - problema",
        "P0101" to "Sensor de fluxo de massa de ar (MAF) - faixa/performance",
        "P0102" to "Sensor de fluxo de massa de ar (MAF) - sinal baixo",
        "P0103" to "Sensor de fluxo de massa de ar (MAF) - sinal alto",
        "P0106" to "Sensor de pressão absoluta do coletor (MAP) - faixa/performance",
        "P0107" to "Sensor MAP - sinal baixo",
        "P0108" to "Sensor MAP - sinal alto",
        "P0110" to "Circuito do sensor de temperatura do ar admitido (IAT) - problema",
        "P0111" to "Sensor IAT - faixa/performance",
        "P0112" to "Sensor IAT - sinal baixo",
        "P0113" to "Sensor IAT - sinal alto",
        "P0115" to "Circuito do sensor de temperatura do líquido de arrefecimento (ECT) - problema",
        "P0116" to "Sensor ECT - faixa/performance",
        "P0117" to "Sensor ECT - sinal baixo",
        "P0118" to "Sensor ECT - sinal alto",
        "P0120" to "Circuito do sensor de posição da borboleta (TPS) - problema",
        "P0121" to "Sensor TPS - faixa/performance",
        "P0122" to "Sensor TPS - sinal baixo",
        "P0123" to "Sensor TPS - sinal alto",
        "P0125" to "Temperatura do líquido de arrefecimento insuficiente para malha fechada",
        "P0130" to "Sonda lambda (banco 1, sensor 1) - circuito com defeito",
        "P0131" to "Sonda lambda (banco 1, sensor 1) - sinal baixo",
        "P0132" to "Sonda lambda (banco 1, sensor 1) - sinal alto",
        "P0133" to "Sonda lambda (banco 1, sensor 1) - resposta lenta",
        "P0134" to "Sonda lambda (banco 1, sensor 1) - sem atividade detectada",
        "P0135" to "Sonda lambda (banco 1, sensor 1) - aquecedor com defeito",
        "P0136" to "Sonda lambda (banco 1, sensor 2) - circuito com defeito",
        "P0141" to "Sonda lambda (banco 1, sensor 2) - aquecedor com defeito",
        "P0170" to "Correção de combustível (banco 1) - problema",
        "P0171" to "Mistura pobre (banco 1)",
        "P0172" to "Mistura rica (banco 1)",
        "P0174" to "Mistura pobre (banco 2)",
        "P0175" to "Mistura rica (banco 2)",
        "P0200" to "Circuito do injetor - problema",
        "P0201" to "Circuito do injetor - cilindro 1",
        "P0202" to "Circuito do injetor - cilindro 2",
        "P0203" to "Circuito do injetor - cilindro 3",
        "P0204" to "Circuito do injetor - cilindro 4",
        "P0217" to "Superaquecimento do motor",
        "P0230" to "Circuito primário da bomba de combustível - problema",
        "P0261" to "Circuito do injetor cilindro 1 - sinal baixo",
        "P0300" to "Falha de ignição detectada em múltiplos cilindros (aleatória)",
        "P0301" to "Falha de ignição detectada no cilindro 1",
        "P0302" to "Falha de ignição detectada no cilindro 2",
        "P0303" to "Falha de ignição detectada no cilindro 3",
        "P0304" to "Falha de ignição detectada no cilindro 4",
        "P0325" to "Circuito do sensor de detonação (knock) - problema",
        "P0326" to "Sensor de detonação - faixa/performance",
        "P0335" to "Circuito do sensor de rotação (CKP) - problema",
        "P0336" to "Sensor CKP - faixa/performance",
        "P0339" to "Sensor CKP - sinal intermitente",
        "P0340" to "Circuito do sensor de fase (CMP) - problema",
        "P0341" to "Sensor CMP - faixa/performance",
        "P0343" to "Sensor CMP - sinal alto",
        "P0400" to "Fluxo de recirculação dos gases de escape (EGR) - problema",
        "P0401" to "EGR - fluxo insuficiente",
        "P0402" to "EGR - fluxo excessivo",
        "P0420" to "Eficiência do catalisador abaixo do limite (banco 1)",
        "P0430" to "Eficiência do catalisador abaixo do limite (banco 2)",
        "P0440" to "Sistema de controle de emissões evaporativas (EVAP) - problema",
        "P0441" to "EVAP - fluxo de purga incorreto",
        "P0442" to "EVAP - vazamento pequeno detectado",
        "P0446" to "EVAP - circuito de controle de ventilação - problema",
        "P0451" to "Sensor de pressão do EVAP - faixa/performance",
        "P0455" to "EVAP - vazamento grande detectado",
        "P0460" to "Circuito do sensor de nível de combustível - problema",
        "P0500" to "Circuito do sensor de velocidade do veículo (VSS) - problema",
        "P0505" to "Sistema de controle de marcha lenta - problema",
        "P0506" to "Marcha lenta abaixo do esperado",
        "P0507" to "Marcha lenta acima do esperado",
        "P0562" to "Tensão do sistema abaixo do normal",
        "P0563" to "Tensão do sistema acima do normal",
        "P0600" to "Circuito de comunicação serial - problema",
        "P0601" to "Erro de checksum na memória de controle interna (ECU)",
        "P0605" to "Erro de ROM da unidade de controle (ECU)",
        "P0700" to "Sistema de controle da transmissão - código armazenado (ver módulo TCM)",
        "P0740" to "Circuito do embreagem do conversor de torque - problema",
        "P2096" to "Correção da mistura pós-catalisador fora da faixa (banco 1)",
        "P2097" to "Correção da mistura pós-catalisador fora da faixa (banco 2)",
        "P2135" to "Correlação entre sensores TPS/pedal - fora de faixa",
        "P2270" to "Sonda lambda (banco 1, sensor 2) - sinal fixo em pobre",
        "P2271" to "Sonda lambda (banco 1, sensor 2) - sinal fixo em rico",
        "C0035" to "Sensor de velocidade da roda dianteira esquerda - circuito",
        "C0040" to "Sensor de velocidade da roda dianteira direita - circuito",
        "B0001" to "Circuito de disparo do airbag do motorista - problema",
        "U0001" to "Barramento de comunicação de alta velocidade (CAN) - problema",
        "U0100" to "Perda de comunicação com o módulo de controle do motor (ECM/PCM)",
        "U0101" to "Perda de comunicação com o módulo de controle da transmissão (TCM)",
    )

    /**
     * Retorna a descrição SAE genérica pro código, ou null se o código não estiver catalogado
     * aqui (ex.: faixa "fabricante" P1xxx, ou um código genérico ainda não adicionado ao mapa).
     */
    fun lookup(code: String): String? = GENERIC[code.uppercase()]
}
